### ISSUE TITLE
Underwater networked portals skip directly to complete state.

### ISSUE THREAD

**Issue by Pheotis** [the-lockedcraft-legacy-organization/Stargate-Bukkit#3]
Networked and random portals do not work underwater.

Sign selection for networked portals leads to invalid destination error.
Random portals activate, but do not detect player entry.

#### Background
A portal without a destination specified is a networked portal. A networked portal with a the r flag is a random portal. A portal with a closing-block specified as water is an underwater portal.

## Description.
If a networked (or by extension, random) portal is created underwater, it will not be usable; selecting a destination and activating the portal will appear successful, but the portal will never activate.

# Repro steps
1. Make two or three networked and/or random underwater portals, for example,
```
Test1

TestNet

```
```
Test2

TestNet

```
```
Test3

TestNet
r
```
2. Select a destination from one of the portals (not applicable for a random portal), and activate it.
3. The issue will appear.

# Summary of Investigation
_Thank you to the user @Thorinwasher for this observation:_

It would appear that, in this specific circumstance, the activation event is being called twice.

When the activation mechanism (in this case, `dead_tube_coral_wall_fan`) is used, the gate opens.
When a player enters the portal, it is treated as a separate occurrence of the activation event; ultimately, the gate closes.
When the activation mechanism is used with the gate already being active, the gate closes.

In this case, the activation occurs, the gate opens, then occurs again, and therefore, closes the gate.

This appears to be related to line 935 of `stargate.java`.

**Comment by Pheotis** [comment]
Random portals now work underwater.
There remains an issue with selecting destinations on underwater portals' signs.

**Comment by Pheotis** [comment]
Some testing later, the following determinations have been made:

 - The sign properly scrolls through the network
 - The network is properly identified, and the list of valid portals is correct
 - When selecting (with the dead coral), the correct gate data is sent
 - Despite sending the correct gate data, the portal does not activate.
 - After selected (with the dead coral), the portal validates itself and resets the sign.

Avenue of investigation will now shift to the activation of the portal itself.

Note that, despite extensive debugging, no differences in console have yet been produced between the working (above ground) and dysfunctional (below ground) portals.

**Comment by Pheotis** [comment]
Our efforts thus far at troubleshooting this issue have proven unsuccessful (our last serious attempt was months ago)

This issue appears to be highly temperamental; on the surface, its cause is not overtly apparent.
As issue is not game-breaking, for now, we have chosen to direct LCLO resources elsewhere.

Therefore, we will open this to pull requests and ask for help from within our community.
A complete repro guide will be posted here at some point over the next few days.

**Comment by Pheotis** [comment]
Underwater networked (no desti) portals appear to now cause a directional error.

```
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData cannot be cast to class org.bukkit.block.data.Directional (org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData and org.bukkit.block.data.Directional are in unnamed module of loader 'app')
        at net.TheDgtl.Stargate.Portal.createPortal(Portal.java:1212) ~[?:?]
        at net.TheDgtl.Stargate.Stargate$bListener.onSignChange(Stargate.java:999) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Paper-337]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-337]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-337]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2803) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$16(PlayerConnection.java:2756) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:324) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:338) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-337]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Pheotis** [comment]
Underwater network portals only cause the above error when they are connecting to a non-empty network... 🤔

**Comment by Pheotis** [comment]
The above bug is very inconsistent. Sometimes, it casts just fine and you can make non-empty open networked portals as normal.

**Comment by Pheotis** [comment]
Now that underwater networked portals are not causing a stack trace, the original issue is once again present. Going to split the directional error into a new issue.

**Comment by Pheotis** [comment]
__**Update**__

Underwater portals appear to be activating twice when they are networked.
Thank you @thorinwasher for pointing that out.

**Comment by Pheotis** [comment]
~ Edited the original post to include a better description of the issue; summarized recent findings.
~ Cleaned up comment thread to only include those findings (by mistake, issue #8 had been merged into this thread).
