### ISSUE TITLE
Underwater networked portals can experience a directional issue when activated.

### ISSUE THREAD

**Issue by Pheotis** [the-lockedcraft-legacy-organization/Stargate-Bukkit#6]
Tested with underwater portals, but probably works with normal portals as well.

**Comment by Pheotis** [comment]
Possibly instance issue?
```
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData cannot be cast to class org.bukkit.block.data.Directional (org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData and org.bukkit.block.data.Directional are in unnamed module of loader 'app')
        at net.TheDgtl.Stargate.Portal.createPortal(Portal.java:1212) ~[?:?]
        at net.TheDgtl.Stargate.Stargate$bListener.onSignChange(Stargate.java:999) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Paper-337]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-337]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-337]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2803) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$16(PlayerConnection.java:2756) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:324) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:338) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-337]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Pheotis** [comment]
Not the N flag: appears to occur on any flag used with a network (no desti) portal.
Works above water though for some reason... going to merge with issue #3

**Comment by Pheotis** [comment]
Appears to be related to #3; closing for that reason.
